name: 'Maven Build'

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up corretto17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven


      - name: Build with Maven (Debug)
        run: mvn -B package -e -X --file pom.xml


      - name: Print Surefire report
        run: cat target/surefire-reports/*.txt || true


  publish-job:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout av kod
        uses: actions/checkout@v4
      - name: Setup av Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - name: Laddar upp artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
